### ISSUE TITLE
Conflicting module names breaks module loading

### ISSUE THREAD

**Issue by billccn** [webjars/moment-timezone#4]
The shim in the pom refers to `momentjs` yet the actual JS programmatically load the `moment` module. According to the third bullet point in the [doc](http://requirejs.org/docs/errors.html#timeout), this is not going to work.

The shim should be changed to require `moment` instead.

**Comment by jamesward** [comment]
Thanks for the heads up.  This fix will be released shortly as `0.4.0-1`.
